services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: techevents
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-network

volumes:
  pgdata:

networks:
  spring-network: